; Base variant of BirbMesh-One based on NRF52 ProMicro
[env:birbmesh_one]
extends = env:nrf52_promicro_diy_tcxo
board_level = extra
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/diy/birbmesh_one>
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/diy/birbmesh_one
  -D NRF52_PROMICRO_DIY

; NRF52 ProMicro + EBYTE E22P-868M30S
[env:birbmesh_one_e22p]
extends = env:birbmesh_one
build_flags = ${env:birbmesh_one.build_flags}
  -DPRIVATE_HW
  -DUSE_EBYTE_E22P

; No-logging variant of BirbMesh-One
[env:birbmesh_one_nolog]
extends = env:birbmesh_one
build_flags = ${env:birbmesh_one.build_flags}
  -DDEBUG_MUTE

; No-logging variant of BirbMesh-One + EBYTE E22P-868M30S
[env:birbmesh_one_e22p_nolog]
extends = env:birbmesh_one_e22p
build_flags = ${env:birbmesh_one_e22p.build_flags}
  -DDEBUG_MUTE

