; DuraHydra - ESP32-S3-ZERO based Meshtastic DIY hardware
; Chip: ESP32-S3 (QFN56, rev 0.2), 4MB QIO Flash (XMC), 2MB OPI PSRAM (AP_3v3)
[env:durahydra]
custom_meshtastic_hw_model = 39
custom_meshtastic_hw_model_slug = DURAHYDRA
custom_meshtastic_architecture = esp32s3
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = DuraHydra
custom_meshtastic_tags = DIY

extends = esp32s3_base
board = esp32-s3-zero
board_level = extra
;board_check = true
board_upload.flash_size = 4MB
board_build.partitions = partition-table.csv
board_build.arduino.memory_type = qio_opi
upload_speed = 921600
monitor_speed = 115200
build_flags =
  ${esp32s3_base.build_flags}
  -D DIY_V1
  -D USE_EBYTE_E22P
  -D BOARD_HAS_PSRAM
  -I variants/esp32s3/diy/durahydra
  -ULED_BUILTIN

